session_name: dev
windows:
  - window_name: vim
    focus: true 
    panes:
    - shell_command:
            - cd $PROJECT_ROOT
            - clear
            - vim .
  - window_name: shell
    panes:
    - shell_command:
            - cd $PROJECT_ROOT
            - clear
  - window_name: mongo
    panes:
    - shell_command:
            - mongo
            - clear
